// Styles
import './styles/base.css'
import './styles/nav.css'
import './styles/hero.css'
import './styles/plans.css'
import './styles/multi.css'
import './styles/checkout.css'
import './styles/chatbot.css'
import './styles/pages.css'
import './styles/member.css'
import './styles/footer.css'
import './styles/utilities.css'
import './styles/desktop.css'

// JS Modules
import './js/navigation.js'
import './js/tabs.js'
import './js/plans.js'
import './js/multi.js'
import './js/checkout.js'
import './js/chatbot.js'
import './js/member.js'
import './js/support.js'
import './js/init.js'
